"""Fix foreign key reference

Revision ID: 9a0cb255ff6f
Revises: 
Create Date: 2024-11-19 10:16:55.360743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0cb255ff6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motivations',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_motivations_message_id'), 'motivations', ['message_id'], unique=False)
    op.create_table('nutritional_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nutritionist', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nutritionist'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_nutritional_plans_plan_id'), 'nutritional_plans', ['plan_id'], unique=False)
    op.create_table('meal_plans',
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['nutritional_plans.plan_id'], ),
    sa.PrimaryKeyConstraint('meal_plan_id')
    )
    op.create_index(op.f('ix_meal_plans_meal_plan_id'), 'meal_plans', ['meal_plan_id'], unique=False)
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('name_recipe', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('portion', sa.Float(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=False),
    sa.Column('fats', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('vegan', 'vegetarian', 'omnivorous', name='recipe_type_enum'), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.meal_plan_id'], ),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.create_index(op.f('ix_recipes_recipe_id'), 'recipes', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_recipe_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meal_plans_meal_plan_id'), table_name='meal_plans')
    op.drop_table('meal_plans')
    op.drop_index(op.f('ix_nutritional_plans_plan_id'), table_name='nutritional_plans')
    op.drop_table('nutritional_plans')
    op.drop_index(op.f('ix_motivations_message_id'), table_name='motivations')
    op.drop_table('motivations')
    # ### end Alembic commands ###
